# Generated by Django 2.2.6 on 2019-11-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='username',
        ),
        migrations.AddField(
            model_name='admin',
            name='identifier',
            field=models.CharField(default='user', max_length=40, unique=True),
        ),
    ]
