# Generated by Django 2.2.6 on 2019-11-01 06:41

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191101_1335'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='admin',
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='identifier',
            new_name='username',
        ),
    ]
